baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cjp-theme"
relativeURLs = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
